// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY6EKn9-I85eLMmjf3nOzz2IXN-v9qoCw',
    appId: '1:438218517277:web:5eb4b37f51ee3a29210ff4',
    messagingSenderId: '438218517277',
    projectId: 'exam-saber',
    authDomain: 'exam-saber.firebaseapp.com',
    storageBucket: 'exam-saber.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDekN_qP87dAG3wP_ID76iksB_lgXzULMQ',
    appId: '1:438218517277:android:f7eeb2c94a83385b210ff4',
    messagingSenderId: '438218517277',
    projectId: 'exam-saber',
    storageBucket: 'exam-saber.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXW8c1yhOZw8ZsIzEh1wWJg7PxvYYpI28',
    appId: '1:438218517277:ios:36d5e36ee68aa7a7210ff4',
    messagingSenderId: '438218517277',
    projectId: 'exam-saber',
    storageBucket: 'exam-saber.firebasestorage.app',
    iosBundleId: 'com.example.examSaber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXW8c1yhOZw8ZsIzEh1wWJg7PxvYYpI28',
    appId: '1:438218517277:ios:36d5e36ee68aa7a7210ff4',
    messagingSenderId: '438218517277',
    projectId: 'exam-saber',
    storageBucket: 'exam-saber.firebasestorage.app',
    iosBundleId: 'com.example.examSaber',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY6EKn9-I85eLMmjf3nOzz2IXN-v9qoCw',
    appId: '1:438218517277:web:9eec2ce628ef3661210ff4',
    messagingSenderId: '438218517277',
    projectId: 'exam-saber',
    authDomain: 'exam-saber.firebaseapp.com',
    storageBucket: 'exam-saber.firebasestorage.app',
  );
}
